Task/urls.py
# task_assignment_project/urls.py
# task_assignment_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TaskApp.urls')),
    path('404/', include('TaskApp.urls')),]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'TaskApp.views.custom_404_view'

TaskApp/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('goals/', goals, name="goals"),
    path('index/', index, name="index"),
    path('contact/', contact, name="contact"),
    path('registerAdmin/', registerAdmin, name="registerAdmin"),
    path('loginAdmin/', loginAdmin, name="loginAdmin"),
    path('about/', about, name="about"),
    path('task_list/<int:task_id>/', task_list, name='task_list'),
    path('dashboard/', dashboard, name='dashboard'),
    path('addTask/', addTask, name='addTask'),
    path('signup/', signup, name="signup"),
    path('signin/', signin, name="signin"),
    path('update_password/', update_password, name='update_password'),
    path('signout/', signout, name="signout"),
    path('update_user/<int:user_id>/', update_user_view, name='updateUser'),
    path('add_goal/', add_goal, name='add_goal'),
    path('update_goal/<int:goal_id>/', update_goal, name='update_goal'),
    path('delete_goal/<int:goal_id>/', delete_goal, name='delete_goal'),
    path('delete_user/', delete_user, name="delete_user"),
    path('completed_goals/', completed_goals, name="completed_goals"),
    path('complete_task/<int:task_id>/', complete_task, name='complete_task'),
    path('users/<int:user_id>/', view_single_user, name='view_single_user'),
    path('view-users/', viewUsers, name='view_users'),
    path('view-tasks/', viewTasks, name='view_tasks'),
    path('view-contacts/', view_contacts, name='view_contacts'),
    path('view-goals/', viewGoals, name='view_goals'),
    path('create-task/', create_task, name='create_task'),
    path('update-task/<int:task_id>/', update_task, name='update_task'),
    path('delete-task/<int:task_id>/', delete_task, name='delete_task'),
    path('forgot_password/', forgot_password, name='forgot_password'), 
    path('create/', create_blog, name='create_blog'),
    path('update/<int:blog_id>/', update_blog, name='update_blog'),
    path('delete/<int:blog_id>/', delete_blog, name='delete_blog'),
    path('blog_list/', blog_list, name='blog_list'),
    path('reset_password/<str:uidb64>/<str:token>/', reset_password, name='reset_password'),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


TaskApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Register_table(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username=models.EmailField(max_length=255,null=True)
    contact_number = models.IntegerField()
    password = models.CharField(max_length=200)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=200, null=True, blank=True, default="Male")
    added_on = models.DateField(auto_now_add=True, null=True, blank=True)
    uploaded_on = models.DateField(auto_now_add=True, null=True, blank=True)
    

    def __str__(self):
        return str(self.user.username)
    

class Goals(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    images = models.ImageField(upload_to="goal_images", null=True, blank=True)
    
    def __str__(self):
        return self.title

class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    images = models.FileField(upload_to="task_images", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    goal = models.ForeignKey(Goals, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False) 

    def __str__(self):
        return self.title

class UserTaskImage(models.Model):
    user = models.ForeignKey(Register_table, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    completed_image = models.ImageField(upload_to="user_completed_images", null=True, blank=True , default=False)
    is_completed = models.BooleanField(default=False) 
    date_uploaded = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return f"User: {self.user.user.username} - Task: {self.task.title}"


class ContactMessage(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username=models.EmailField(max_length=255)
    password = models.CharField(max_length=200,default="",null=True)
    
    def __str__(self):
        return self.username
    
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    author=models.TextField()

    def __str__(self):
        return self.title
    



TaskApp/views.py

from .models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.sessions.backends.db import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib import messages
from django.contrib.auth import authenticate, login
from .models import Register_table
from django.contrib.auth.models import User
from django.utils.encoding import force_bytes



def index(request):
    blogs=Blog.objects.all()
    return render(request,'homepage_1.html',{"blogs":blogs})

def about(request):
    return render(request,'aboutus.html')

@login_required
def task_list(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    user = request.user
    try:
        user_task_image = UserTaskImage.objects.get(user=user.register_table, task=task)
        is_completed = user_task_image.is_completed
    except UserTaskImage.DoesNotExist:
        is_completed = False

    com = UserTaskImage.objects.all()
    context = {'user': user, 'task': task, 'com': com, 'is_completed': is_completed}
    return render(request, 'task.html', context)

@login_required
def completed_goals(request, user_id):
    completed_tasks = UserTaskImage.objects.filter(user__id=user_id, is_completed=True)

    context = {
        'completed_tasks': completed_tasks,
    }

    return render(request, 'completed_goals.html', context)


@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    user = request.user.register_table

    if request.method == 'POST':
        try:
            user_task_image = UserTaskImage.objects.get(user=user, task=task)
        except UserTaskImage.DoesNotExist:
            user_task_image = UserTaskImage.objects.create(user=user, task=task)

        completed_image = request.FILES.get('completed_image')

        if completed_image:
            if user_task_image.completed_image:
                # If a file already exists, update it with the new file
                user_task_image.completed_image.delete()  # Delete the old file
            user_task_image.completed_image = completed_image
            user_task_image.is_completed = True  # Set is_completed to True when the image is uploaded
            user_task_image.save()

            # Mark the task as completed
            task.completed = True
            task.save()

            messages.success(request, f'Task "{task.title}" completed successfully!')
        else:
            messages.warning(request, 'Please upload a completed image.')

        return redirect('/goals', task_id=task.id)

    # Handle cases where the request method is not POST
    return render(request, 'goals.html')


def signup(request):
    if request.method == 'POST':
        email = request.POST['email']
        contact_number = request.POST['contact_number']
        password = request.POST['password']
        age = request.POST.get('age', None)
        gender = request.POST.get('gender', 'Male')

        # Check if the username (email) already exists
        if User.objects.filter(username=email).exists():
            messages.error(request, 'Username already exists')

            # Username (email) already exists, you can handle this case (e.g., show an error message)
            return render(request, 'Login.html', {'error_message': 'Username already exists'})

        # Username is unique, create User and Register_table instances
        user = User.objects.create_user(username=email, password=password)
        register_table = Register_table(user=user, username=email, contact_number=contact_number, password=password, age=age, gender=gender)
        register_table.save()

        # Authenticate and log in the user
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/index')  # Redirect to the home page or any other desired page

    return render(request, 'Login.html')


def signin(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/index')  # Redirect to the home page or any other desired page
        else:
            # Handle invalid login
            return render(request, 'Login.html', {'error_message': 'Invalid login credentials'})

    return render(request, 'Login.html')



def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        user = User.objects.filter(username=email).first()

        if user is not None:
            # Generate a password reset token
            token = default_token_generator.make_token(user)

            # Build the password reset URL
            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            reset_url = reverse('reset_password', kwargs={'uidb64': uidb64, 'token': token})
            reset_url = request.build_absolute_uri(reset_url)

            # Send a password reset email
            subject = 'Reset Your Password'
            message = f'Click the following link to reset your password: {reset_url}'
            from_email = 'example@gmail.com'  # Replace with your email address
            to_email = [user.email]
            
            send_mail(subject, message, from_email, to_email)

            # Inform the user about the email
            messages.success(request, 'Password reset email sent successfully. Check your inbox.')
            return render(request, 'forgot_password_success.html')

    return render(request, 'forgot.html')

def reset_password(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            new_password = request.POST['new_password']
            user.set_password(new_password)
            user.save()

            # Log in the user after password reset
            authenticated_user = authenticate(request, username=user.username, password=new_password)
            login(request, authenticated_user)

            messages.success(request, 'Password successfully reset. You are now logged in.')
            return redirect('/index')  # Redirect to the home page or any other desired page

        return render(request, 'reset_password.html', {'uidb64': uidb64, 'token': token})
    else:
        messages.error(request, 'Invalid password reset link. Please try again.')
        return render(request, 'login.html') 

@login_required
def update_password(request):
    if request.method == 'POST':
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        if new_password == confirm_password:
            # Check if the user is authenticated
            if request.user.is_authenticated:
                # Update the user's password
                request.user.set_password(new_password)
                request.user.save()

                # Update the user's session to reflect the new password
                update_session_auth_hash(request, request.user)

                messages.success(request, 'Password updated successfully.')
                return redirect('/index')  # Redirect to the home page or any other desired page
            else:
                messages.error(request, 'User not authenticated.')
                return redirect('/signin')  # Redirect to the login page
        else:
            messages.error(request, 'Password and Confirm Password do not match.')
            return redirect('update_password')

    return render(request, 'update_password.html')

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        ContactMessage.objects.create(
            name=name,
            email=email,
            subject=subject,
            message=message
        )

        messages.success(request, 'Your message has been sent successfully!')
        return redirect('contact')

    return render(request, 'contact.html')

@login_required
def goals(request):
    all_goals = Goals.objects.all()
    goals_and_tasks = []

    for goal in all_goals:
        tasks_for_goal = Task.objects.filter(goal=goal)
        goals_and_tasks.append({'goal': goal, 'tasks': tasks_for_goal})

    return render(request, 'goals.html', {'goals_and_tasks': goals_and_tasks})


def registerAdmin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Check if the username already exists
        if User.objects.filter(username=username).exists():

TaskApp/templates/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>

    <style>
      @import url("https://fonts.googleapis.com/css?family=Montserrat:400,800");

      * {
        box-sizing: border-box;
      }

      body {
        background: #f6f5f7;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        font-family: "Montserrat", sans-serif;
        height: 100vh;
        margin: -20px 0 50px;
      }

      h1 {
        font-weight: bold;
        margin: 0;
      }

      h2 {
        text-align: center;
      }

      p {
        font-size: 14px;
        font-weight: 100;
        line-height: 20px;
        letter-spacing: 0.5px;
        margin: 20px 0 30px;
      }

      span {
        font-size: 12px;
      }

      a {
        color: #333;
        font-size: 14px;
        text-decoration: none;
        margin: 15px 0;
      }

      button {
        border-radius: 20px;
        border: 1px solid #ff4b2b;
        background-color: #ff4b2b;
        color: #ffffff;
        font-size: 12px;
        font-weight: bold;
        padding: 12px 45px;
        letter-spacing: 1px;
        text-transform: uppercase;
        transition: transform 80ms ease-in;
      }

      button:active {
        transform: scale(0.95);
      }

      button:focus {
        outline: none;
      }

      button.ghost {
        background-color: transparent;
        border-color: #ffffff;
      }

      form {
        background-color: #ffffff;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 0 50px;
        height: 100%;
        text-align: center;
      }

      input {
        background-color: #eee;
        border: none;
        padding: 12px 15px;
        margin: 8px 0;
        width: 100%;
      }

      .container {
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25),
          0 10px 10px rgba(0, 0, 0, 0.22);
        position: relative;
        overflow: hidden;
        width: 768px;
        max-width: 100%;
        min-height: 100%;
      }

      .form-container {
        position: absolute;
        top: 0;
        height: 100%;
        transition: all 0.6s ease-in-out;
      }

      .sign-in-container {
        left: 0;
        width: 50%;
        z-index: 2;
      }

      .container.right-panel-active .sign-in-container {
        transform: translateX(100%);
      }

      .sign-up-container {
        left: 0;
        width: 50%;
        opacity: 0;
        z-index: 1;
      }

      .container.right-panel-active .sign-up-container {
        transform: translateX(100%);
        opacity: 1;
        z-index: 5;
        animation: show 0.6s;
      }

      @keyframes show {
        0%,
        49.99% {
          opacity: 0;
          z-index: 1;
        }

        50%,
        100% {
          opacity: 1;
          z-index: 5;
        }
      }

      .overlay-container {
        position: absolute;
        top: 0;
        left: 50%;
        width: 50%;
        height: 100%;
        overflow: hidden;
        transition: transform 0.6s ease-in-out;
        z-index: 100;
      }

      .container.right-panel-active .overlay-container {
        transform: translateX(-100%);
      }

      .overlay {
        background: #ff416c;
        background: -webkit-linear-gradient(to right, #ff4b2b, #ff416c);
        background: linear-gradient(to right, #ff4b2b, #ff416c);
        background-repeat: no-repeat;
        background-size: cover;
        background-position: 0 0;
        color: #ffffff;
        position: relative;
        left: -100%;
        height: 100%;
        width: 200%;
        transform: translateX(0);
        transition: transform 0.6s ease-in-out;
      }

      .container.right-panel-active .overlay {
        transform: translateX(50%);
      }

      .overlay-panel {
        position: absolute;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 0 40px;
        text-align: center;
        top: 0;
        height: 100%;
        width: 50%;
        transform: translateX(0);
        transition: transform 0.6s ease-in-out;
      }

      .overlay-left {
        transform: translateX(-20%);
      }

      .container.right-panel-active .overlay-left {
        transform: translateX(0);
      }

      .overlay-right {
        right: 0;
        transform: translateX(0);
      }

      .container.right-panel-active .overlay-right {
        transform: translateX(20%);
      }

      .social-container {
        margin: 20px 0;
      }

      .social-container a {
        border: 1px solid #dddddd;
        border-radius: 50%;
        display: inline-flex;
        justify-content: center;
        align-items: center;
        margin: 0 5px;
        height: 40px;
        width: 40px;
      }

      footer {
        background-color: #222;
        color: #fff;
        font-size: 14px;
        bottom: 0;
        position: fixed;
        left: 0;
        right: 0;
        text-align: center;
        z-index: 999;
      }

      footer p {
        margin: 10px 0;
      }

      footer i {
        color: red;
      }

      footer a {
        color: #3c97bf;
        text-decoration: none;
      }
    </style>
  </head>

  <body>
    <h2></h2>
    <br /><br />
    <div>
      {% for message in messages %} {% if message.tags %}
      <div class="alert alert-danger">{{ message }}</div>
      {% endif %} {% endfor %}
    </div>
    <div class="container" id="container">
      <div class="form-container sign-up-container">
        <form action="{% url 'signup' %}" method="POST">
          {% csrf_token %}

          <h1>Create Account</h1>

          <span>or use your email for registration</span>

          <input
            type="email"
            name="email"
            placeholder="Email"
            id="email"
            class="form-control ms-0"
            required=""
            pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
          />
          <input
            type="password"
            name="password"
            placeholder="Password"
            id="pass1"
            required
            class="form-control ms-0"
            
          />
          <input
            type="tel"
            required
            name="contact_number"
            placeholder="Contact Number"
            id="contact_number"
            title="Enter Correct Phone no"
            class="form-control ms-0"
            pattern="[0-9]{10}"
            oninput="limitInput(this)"
          />
          <input
            type="text"
            name="age"
            placeholder="Age"
            id="age"
            class="form-control ms-0"
            pattern="[0-9]+"
            title="Please enter a valid age (numeric value)"
          />
          <label for="gender">Gender:</label>
          <select name="gender" id="gender" class="form-control ms-0">
            <option value="Male">Male</option>
            <option value="Female">Female</option>
            <option value="Other">Other</option>
            <!-- Fix the value for 'Other' option -->
            <!-- Add more options if needed -->
          </select>
          <br />

          <button
            style="cursor: pointer"
            type="submit"
            value="SignUp"
            class="btn btn-primary mx-auto"
            id="submitbtn"
          >
            Sign Up
          </button>
        </form>
      </div>

      <div class="form-container sign-in-container">
        <form action="{% url 'signin' %}" method="POST">
          {% csrf_token %}
          <h1>Sign in</h1>

          <span>or use your account</span>
          <input
            type="text"
            name="email"
            placeholder="Email"
            id="email"
            class="form-control ms-0"
          />
          <input
            type="password"
            name="password"
            placeholder="Password"
            id="pass1"
            class="form-control ms-0"
          />
          <a href="/contact">Forgot Password ?</a>

          <button type="submit" style="cursor: pointer" value="Login">
            Sign In
          </button>
        </form>
      </div>
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <h1>Welcome Back!</h1>
            <p>
              To keep connected with us please login with your personal info
            </p>
            <button class="ghost" style="cursor: pointer" id="signIn">
              Sign In
            </button>
            <br />
            <h3>
              Back To Home !
              <br />
              <br />
              <a href="/"
                ><button class="ghost" style="cursor: pointer" id="/">
                  Home
                </button></a
              >
            </h3>
          </div>
          <div class="overlay-panel overlay-right">
            <h1>Hello, Friend!</h1>
            <p>Enter your personal details and start journey with us</p>
            <button class="ghost" style="cursor: pointer" id="signUp">
              Sign Up
            </button>
            <h3>
              Back To Home !
              <br />
              <br />
              <a href="/"
                ><button class="ghost" style="cursor: pointer" id="/">
                  Home
                </button></a
              >
            </h3>
          </div>
        </div>
      </div>
    </div>

    <script>
      const signUpButton = document.getElementById("signUp");
      const signInButton = document.getElementById("signIn");
      const container = document.getElementById("container");

      signUpButton.addEventListener("click", () => {
        container.classList.add("right-panel-active");
      });

      signInButton.addEventListener("click", () => {
        container.classList.remove("right-panel-active");
      });
    </script>
  </body>
</html>

TaskApp/templates/adminregister.html
<!-- adminregister.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Registration</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin: 50px;
      }

      h1 {
        color: #333;
      }

      .logo {
        max-width: 100px;
      }

      form {
        max-width: 400px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }

      label {
        display: block;
        margin-bottom: 8px;
        font-weight: bold;
      }

      input {
        width: calc(100% - 30px);
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        display: inline-block;
      }

      .eye-button {
        background-color: transparent;
        border: none;
        cursor: pointer;
        position: relative;
        top: 6px;
        right: 30px;
        display: inline-block;
      }

      button {
        background-color: #28a745;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        display: inline-block;
      }

      button:hover {
        background-color: blueviolet;
      }

      a {
        color: #007bff;
        text-decoration: none;
      }

      a:hover {
        text-decoration: underline;
      }
    </style>
  </head>
  <body>
    <img src="{% static 'images/sdg2.png' %}" alt="" class="logo" />
    <h1>Admin Registration</h1>
    {% if messages %} {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %} {% endif %}
    <form method="post" action="{% url 'registerAdmin' %}">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" required />

      <label for="password">Password:</label>
      <input type="password" name="password" id="password" required />
      <button
        type="button"
        class="eye-button"
        onclick="togglePassword('password')"
      >
        👁️
      </button>

      <button type="submit">Register</button>
    </form>
    <p>
      Already have an account? <a href="{% url 'loginAdmin' %}">Login here</a>
    </p>

    <script>
      function togglePassword(inputId) {
        var passwordInput = document.getElementById(inputId);
        if (passwordInput.type === "password") {
          passwordInput.type = "text";
        } else {
          passwordInput.type = "password";
        }
      }
    </script>
  </body>
</html>

TaskApp/templates/certificate.html
<!-- certificate.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate of Achievement</title>
</head>
<body>
    <h1>Congratulations!</h1>
    <p>You have achieved a milestone and earned a certificate.</p>
    <p>Task Count: {{ certificate.task_count }}</p>
    <img src="{{ certificate.image.url }}" alt="Certificate Image">
</body>
</html>

TaskApp/templates/forgot_password_success.html
{% block content %}
  <h2>Password Reset Email Sent</h2>
  <p>An email with instructions to reset your password has been sent to your registered email address. Please check your inbox.</p>
{% endblock %}

TaskApp/templates/view_single_user.html
<!DOCTYPE html>
<html>
  <head>
    <title>User Details</title>
  </head>
  <body>
    <h1>User Details</h1>
    <p><strong>Username:</strong> {{ user.user.username }}</p>
    <p><strong>Contact Number:</strong> {{ user.contact_number }}</p>
    <p><strong>Age:</strong> {{ user.age }}</p>
    <p><strong>Gender:</strong> {{ user.gender }}</p>

    <h2>Goals</h2>
    {% for goal in goals %}
    <h3>{{ goal.title }}</h3>
    <p><strong>Description:</strong> {{ goal.description }}</p>
    {% if goal.images %}
    <img src="{{ goal.images.url }}" alt="{{ goal.title }} Image" />
    {% endif %}

    <h4>Tasks</h4>
    {% for task in goal.task_set.all %}
    <p><strong>Title:</strong> {{ task.title }}</p>
    <p><strong>Description:</strong> {{ task.description }}</p>
    <p><strong>Created At:</strong> {{ task.created_at }}</p>
    <p><strong>Updated At:</strong> {{ task.updated_at }}</p>
    <p><strong>Completed:</strong> {{ task.completed }}</p>

    {% endfor %} {% endfor %}

    <a href="{% url 'view_users' %}">Back to All Users</a>
  </body>
</html>